### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by OfficalCodeMissile** [MukiTanuki/armor-statues#1]
#### Issue Description:

"You cannot trigger this objective yet" error appears when trying to set an item frame invisible using both the book and the command
#### What happens:
"You cannot trigger this objective yet" error appears when trying to set an item frame invisible using both the book and the command.
This is on a server where all other players are able to use the book to set item frames invisible 

#### What you expected to happen:
The item frame to become invisible popping up a message "Triggered [if_invisible] (set value to 1)"

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.16.5
- Armor Statues: 2.8

- Single Player and/or Server? spigot server
- Optifine? no

**Comment by Phelms215** [comment]
Hello I am running into this error, is it possible to reopen? 

I have discovered the cause is if someone does /trigger if_invisible set 0, afterwards they cannot make anything invisible

**Comment by Phelms215** [comment]
running the "/function armor_statues:uninstall" then disabling and reenabling the datapack fixes it
