### ISSUE TITLE
Installed the datapack into an existing world and can't use it

### ISSUE THREAD

**Issue by ajyoung1234** [MukiTanuki/armor-statues#13]
I added the newest version of the datapack to my singleplayer world, and all the function commands appear and I can give myself the book with the command, but when I try to use it it says "Unknown scoreboard objective 'as_trigger' " 
![2022-10-22_02 31 27](https://user-images.githubusercontent.com/73314145/197324295-ddd691e2-0062-4062-a5b9-57eae0359eca.png)

**Comment by MukiTanuki** [comment]
Not enough information, cannot reproduce.

**Comment by dbrighthd** [comment]
I had the same issue. it was caused by a different datapack having a broken minecraft:load tag, which then made it not load any other datapack's load functions
