### ISSUE TITLE
[BUG] Unable to use : You cannot trigger this objective yet

### ISSUE THREAD

**Issue by emnbdx** [MukiTanuki/armor-statues#14]
#### Issue Description:
I install last version 2.9.2 found on curseforge on my fabric server and nobody can use armor stand.
Book is craftable but everytime user (execpt admin) get error message You cannot trigger this objective yet.

#### What happens:
Error message on tchat : You cannot trigger this objective yet

#### What you expected to happen:
Armor stand move !

#### Steps to reproduce:
I try on another server but I don't reproduce.
Here is what I try on my server
**Check objective** 
/scoreboard objectives list
check for as_trigger in list - OK
**Try to reset everything**
/function armor_statues:uninstall
/datapack disable "file/armor_statues_v2.9.2.zip"
/datapack enable "file/armor_statues_v2.9.2.zip"
**Enable as trigerr for all user**
/scoreboard players enable * as_trigger
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.9.2
- Armor Statues: 2.9.2

- Single Player and/or Server? Fabric server

**Comment by MukiTanuki** [comment]
Not enough information, most likely an issue with mods or plugins. closing
