### ISSUE TITLE
[BUG] Display Name option disappeared from Style settings

### ISSUE THREAD

**Issue by lucashsbifsc** [MukiTanuki/armor-statues#17]
#### Issue Description:
Display Name option disappeared from Style settings

#### What happens:
No option to enable display name of a statue.

#### What you expected to happen:
Enable display name to be able to put a name tag into a armor stand.

#### Steps to reproduce:

1. Open statues book
2. Click into Styles page
3. See that there's no "Display Name" option

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.20.1
- Armor Statues: 2.9.4

- Single Player and/or Server? 
Single Player and Server

- Optifine? 
No, only Iris Shaders and Fabric

#### Screenshots *(Optional)*
![image](https://github.com/MukiTanuki/armor-statues/assets/124683425/902f0733-0482-4837-aad1-2f37888b2fe6)

**Comment by MukiTanuki** [comment]
Not a bug, the way you name armor stand is automatic in the newest version.  see the changelog: https://legacy.curseforge.com/minecraft/customization/armor-statues-datapack/files/4469497
You can rename an armor stand item in an anvil and place it down in order for it to display its name.
