### ISSUE TITLE
Teleportation of Armor Stands 

### ISSUE THREAD

**Issue by ChauDynasty** [MukiTanuki/armor-statues#18]
#### Issue Description:
When you use the undo/redo buttons, you can make armor stands teleport to their previous location anywhere in loaded chunks.

#### What happens:
Armor stands teleport to previous locations.

#### What you expected to happen:

Not sure honestly, was just trying to undo a previous action, but I accidentally hit the button again, and the stand teleported.

#### Steps to reproduce:

1. Use book to move an armor stand, then hit “redo” or “undo”.
2. Break stand and move to another location with the original area still loaded.
3. Place down another stand hit the opposite “undo” or “redo” button from the first step.
4. Stand will teleport back to original location, and then the process can be done repeatedly.
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.2.1
- Armor Statues: 2.10

- Single Player and/or Server? Both
- Optifine? No

**Comment by matdoh** [comment]
don't you mean minecraft version 1.20.1?

**Comment by MukiTanuki** [comment]
Fixed in an upcoming version (1.20.2)
