### ISSUE TITLE
[BUG] Custom name appearing automatically

### ISSUE THREAD

**Issue by Ritcheur** [MukiTanuki/armor-statues#19]
#### Issue Description:
The name of every amor stand in the world is set automatically to visible.

#### What happens:
The custom name of armor stands summoned with "CustomNameVisible:0b", or whose name has been hidden away using the book, appeares automaticlly after a few seconds. This affects every armor stand in a world with the datapack enable.

#### What you expected to happen:
Their name should stay invisible unless specified otherwise.

#### Steps to reproduce:
1. /summon armor_stand ~ ~ ~ {NoGravity:1b,CustomName:'{"text":"test"}',CustomNameVisible:0b}
2. The name should appear regardless of "CustomNameVisible:0b" being specified

____
#### Affected Versions (Do *not* use "latest"): 

- Minecraft: 1.20.1
- Armor Statues: v2.9.4 and V2.9.3 but not V2.9.2
- Paper 1.20.1 Server

#### Screenshots *(Optional)*
See video on youtube :
https://youtu.be/P_iGJwx50xs

**Comment by MukiTanuki** [comment]
As of v2.9.3, armor stands with custom names automatically makes the names visible.  As such changing CustomNameVisible via the armor stands book was removed in favor of this feature.
See the changelog here:
https://legacy.curseforge.com/minecraft/customization/armor-statues-datapack/files/4469497
If you'd like it to not be visible, you can either remove the name from the armor stand before summoning it, set the armor stand as invulnerable, or a marker.
