### ISSUE TITLE
Tool rack

### ISSUE THREAD

**Issue by Yollan-E** [MukiTanuki/armor-statues#2]
When i put something on a tool rack using the book, it stays like that forever, i cant destroy the armourstand neither in survival or creative, i cant change it using the book itself and i cant get rid of it using /function armor_statues:admin/unused. 

Is there a way to fix this that ive missed or is it bugged and i can never get rid of it?

**Comment by MukiTanuki** [comment]
You can use the Armor Statues book to fix this.  You need to "unlock" the armor stand first, then set it to be not invisible.

**Comment by MukiTanuki** [comment]
As a small note, this issue has been resolved in the next upcoming patch for 1.17!
