### ISSUE TITLE
[BUG] Armor Stand gains back visibility

### ISSUE THREAD

**Issue by matdoh** [MukiTanuki/armor-statues#21]
#### Issue Description:
an invisible set armor stand gains back his visibility after i take his main hand item. 

#### What happens:
an armor stand wont stay invisible without an main-hand item. making an empty armor stand invisible is completely impossible. The issue sounds similar to the one with the custom names

#### What you expected to happen:
the armor stand should become more precisely stay invisible under every condition

#### Steps to reproduce:

1. spawn armorstand
2. (optional: give him arms and an item)
3. make it invisible using the book or /trigger as_trigger set 10
4. (when he carries an item, take it away
5. bug occurs
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.20.1
- Armor Statues: 2.9 and 2.10

- Single Player and/or Server? both
- Optifine? yes

**Comment by MukiTanuki** [comment]
If an armor stand has no items in its inventory the datapack will automatically set it to be visible.  This is to make certain that servers aren't filled with invisible armor stands that they are unable to remove without the AS book.
