### ISSUE TITLE
if_invisible doesn't work on Glow Item Frame

### ISSUE THREAD

**Issue by JGTB0PL** [MukiTanuki/armor-statues#22]
#### Issue Description:
/trigger if_invisible works on regular item frames but not the glowy ones

#### Steps to reproduce:

1. look at the glow item frame
2. trigger if_invisible
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: tested on 1.20.x, issue may persist on 1.17+
- Armor Statues: 2.8

- Server running Paper
- No Optifine

**Comment by MukiTanuki** [comment]
You're using an outdated datapack version for your current mc version.
