### ISSUE TITLE
glass blocks colliding while using warped fungus on a stick[BUG]

### ISSUE THREAD

**Issue by LumpyDenommee** [MukiTanuki/armor-statues#24]
#### Steps to reproduce:

1. Place armor stand on stair
2. Take out warped fungus on a stick and wait for the little stained glass blocks to appear on the armor stand
3. Place the legs at a 90 degree angle
4. Click on the black stained glass on the armor stand to lower it on the y axis
5. Once it goes into the stairs, it can no longer be lowered any further
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.20.1
- Armor Statues:

- Single Player and/or Server? Server
- Optifine? Iris

**Comment by MukiTanuki** [comment]
This is a game limitation, not much I can do about this.  What your describing never occurred in previous versions of the datapack.
