### ISSUE TITLE
[BUG] I don't know how the get the book. the command"/trigger as_help" no work.

### ISSUE THREAD

**Issue by Retro-1x1** [MukiTanuki/armor-statues#25]
#### Issue Description:
I don't know how the get the book. the command"/trigger as_help" no work.

#### What happens:

I don't know how the get the book. the command"/trigger as_help" no work.

#### What you expected to happen:

for the command to show me how to get the book

#### Steps to reproduce:

1.type in command. Says "unknown scoreboard objective "as_help"
2. Cant get book.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.20.4
- Armor Statues: curseforge download

- Single Player and/or Server? single player
- Optifine? no

#### Screenshots *(Optional)*
![Screenshot 2024-04-21 102556](https://github.com/MukiTanuki/armor-statues/assets/161983688/f7c785e0-5a20-413d-9243-845c90424637)

**Comment by Daniel99j2** [comment]
Looks like it’s not loaded properly.
Run /datapack list and screenshot the output

**Comment by Retro-1x1** [comment]
> Looks like it’s not loaded properly. Run /datapack list and screenshot the output

output:
![Screenshot 2024-04-24 154351](https://github.com/MukiTanuki/armor-statues/assets/161983688/15f86fce-02f6-400b-a55c-a42071a2b673)

**Comment by Retro-1x1** [comment]
curently using 1.20.5

**Comment by MukiTanuki** [comment]
This datapack isn't yet updated to 1.20.5 yet and the update for this datapack is still in progress.  Mojang has made a lot of game breaking changes in 1.20.5 that may take a while to fully resolve within all of my datapacks, so I do ask for a bit of patience while I make the necessary fixes.

**Comment by Retro-1x1** [comment]
I doesnt work on 1.20.4 either way

**Comment by MukiTanuki** [comment]
> I doesnt work on 1.20.4 either way

from your screenshot it doesn't look like you have the datapack loaded properly.

**Comment by Retro-1x1** [comment]
Then how do I load it?

**Comment by MukiTanuki** [comment]
You place the folder containing the files or zip file in your 'datapack' folder for your world.  There are plenty of tutorials out there for loading in datapacks and this probably isn't the best place to ask about that kind of information.
