### ISSUE TITLE
[BUG] Invisible Amour Stand turns visible when not holding item

### ISSUE THREAD

**Issue by YoavTC** [MukiTanuki/armor-statues#28]
#### Issue Description:
Invisible armour stand turns visible after taking the item it held
#### What happens:
The armour stand returns to a visible state
#### What you expected to happen:
The armour stand to remain invisible
#### Steps to reproduce:

1. Make armour stand hold item
2. Make armour stand invisible
3. Take item back from armour stand
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.20.6 vanilla
- Armor Statues: v2.12

- Java Realms
- Not using optifine

#### Screenshots *(Optional)*

https://github.com/MukiTanuki/armor-statues/assets/107130059/dbc82bbd-c99f-44ac-b347-fc5ea5618005

**Comment by MukiTanuki** [comment]
Not a bug, this is intentional.  Since invisible armor stands are also invulnerable this is done to reduce unnecessary clutter on servers and in the world.
