### ISSUE TITLE
Empty book

### ISSUE THREAD

**Issue by Blackmadman** [MukiTanuki/armor-statues#29]
#### Issue Description: 
Empty book

#### What happens: 
When you create the book, it only has blank pages.

#### Steps to reproduce:

1. placing an armor stand and a book in a crafting table
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.20.6
- Armor Statues: 2.11.0

- Single Player and/or Server?: Server (Paper 1.20.6)
- Optifine?: No

**Comment by Blackmadman** [comment]
I forgot: no other datapacks are installed.

**Comment by MukiTanuki** [comment]
try doing a /reload, then see if it's still an issue.  It's most likely a problem with paper.

**Comment by Blackmadman** [comment]
It is the same even after reload. 10 empty pages. And as I have seen, I am not the only one with this problem. A friend also told me that he has the same problem with the original server software, without Spigot or Paper. Maybe it's the Datapack after all?

**Comment by MukiTanuki** [comment]
did you /reload, then craft a new book?

**Comment by Blackmadman** [comment]
Yes, I have done that. Still 10 blank pages. And players on the server do not have the rights to reload plugins. I don't want to assign them.

**Comment by MukiTanuki** [comment]
This is most likely an issue with paper.  Unfortunately I'd need more info to come up with a fix for this.  Try running it on a vanilla or fabric server and see if the issue still persists.

**Comment by MukiTanuki** [comment]
> Yes, I have done that. Still 10 blank pages. And players on the server do not have the rights to reload plugins. I don't want to assign them.

I would also recommend trying the latest version v2.11.1

**Comment by Blackmadman** [comment]
It works with the new version. Super :) Thanks for the bug fix.
