### ISSUE TITLE
Allow players to make armor stands appear on fire

### ISSUE THREAD

**Issue by pine1needle** [MukiTanuki/armor-statues#3]
1.17 introduced a new NBT tag called HasVisualFire that causes entities to appear on fire even if they are not actually on fire. It would be a cool feature if the book in this datapack allowed players to toggle that tag for their armor stands, so that builders can have characters in their scenes be on fire (without having to place the armor stand in lava).

**Comment by pine1needle** [comment]
I also suggested this at the [Vanilla Tweaks feedback page](https://vanillatweaks.net/feedback/) before I realized that this repository existed.

**Comment by MukiTanuki** [comment]
Thank you for the suggestion!  While AS is on the Vanilla Tweaks page, it's not technically associated with them and I don't see the suggestions that are made to it.
Anyone is more than welcome to give suggestions on the Curseforge or here though!

**Comment by MukiTanuki** [comment]
Done for 1.19.4!
