### ISSUE TITLE
Item Frame Animation Help

### ISSUE THREAD

**Issue by Hawkae12** [MukiTanuki/armor-statues#30]
Hello, I am playing with my friends and family on a Minecraft server and we have your datapack installed. I went to do some animations using the item frame and book with redstone following everything the YouTuber TangoTek did (https://www.youtube.com/watch?v=oUHDVToXVyI) but learned that you have to enable it before it works. So I did some research and tried to figure it out and discovered that there was the "/function armor_statues:animate" command (might not be identical to the actual command) and ran it but I still couldn't get it to work. I don't know if this is the right spot to post something like this but can you help me figure out how to enable armor statue animations? Thank you, have a wonderful day.

**Comment by Hawkae12** [comment]
Also for clarification we are using armor_statues_v2.9.4 from the hermitcraft season 9 world download. And what I mean by enable animations is that when you read the change log of this datapack it says that item frame animations were added and the first point for it says that it is disabled by default, the enabling is what I don't know how to do it.

**Comment by MukiTanuki** [comment]
you can use newer versions, but you can use "/function armor_statues:admin" to change animate time for item frames.  setting it above zero activates this functionality.
