### ISSUE TITLE
[BUG] Rotation for right arm is not consistent with the X axis after using "block on surface" preset.

### ISSUE THREAD

**Issue by mcfrei** [MukiTanuki/armor-statues#4]
#### Issue Description:

First of all, thanks for all the wonderful work!
I am making a wither statue for Halloween at spawn and having troubles with the wither's tail part.
Is there any way to rotate the block in the stand's right arm consistently around the world or stand axis?

#### What happens:

Right arm rotates up and to the side a bit.

#### What you expected to happen:

Right arm rotates so that the block rotates around the X axis only.

#### Steps to reproduce:

1. Set a new stand. Set arms visible. Put a block in right arm. 
2. Use "Auto align > Block on surface"
3.  Set stand visible. Use "Pose adjustment > R.Arm X+" 

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.17.1
- Armor Statues: 2.8

- Single Player and/or Server? Server.
- Optifine? None.

#### Screenshots *(Optional)*
![image](https://user-images.githubusercontent.com/37238771/133907598-6a04eeaa-65ab-4f5c-be47-0912f502083b.png)

**Comment by mcfrei** [comment]
I think it's probably the intended behavior but it also could be the issue of applying a rotation quaternion after setting up the hand for the "block on surface" preset. If you could point me to the part where you do rotational math I could test my assumptions and maybe help develop a fix. Darn quaternions, always wanting to catch a honest programmer off-guard!

**Comment by MukiTanuki** [comment]
This is more of an issue with the way minecraft renders armor stand appendage rotations than with the datapack itself.  When you use the adjustments for x/y/z you're adjusting for the rotation of the x/y/z of that appendage in the nbt. (these rotations are relative to the other rotations, so adjusting them can have mixed results).  As such I'm closing the issue as this is a vanilla "feature".  Thank you for writing the report though!

**Comment by mcfrei** [comment]
Gotcha. I'm still gonna see if anything can be done with that, because it was very annoying to not be able to rotate the block correctly. I ended up with using player heads.
Here's how it looks sort of finished.
![image](https://user-images.githubusercontent.com/37238771/134685088-bd74eee8-2b9f-4c1e-9914-8e23b2adca12.png)
![image](https://user-images.githubusercontent.com/37238771/134685203-e77917b0-2859-4404-866e-d729c80fc6bf.png)
