### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by UniverseSteve** [MukiTanuki/armor-statues#6]
#### Issue Description:
when using with Project Korra plugin it breaks the triggers so now i cannot use the plugin

#### What happens:
well it breaks how the datapack works 

#### What you expected to happen:
being able to use it

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:
- Armor Statues:

- Single Player and/or Server?
- Optifine?

**Comment by MukiTanuki** [comment]
This is a bug with Project Korra, not Armor Statues.  Closing as invalid.
