### ISSUE TITLE
[FEATURE] align blocks and heads in various rotations to surface

### ISSUE THREAD

**Issue by mcfrei** [MukiTanuki/armor-statues#8]
#### Issue Description:

First of all, thanks again for amazing and cool things. I'm looking for a way to reliably tile blocks, heads and items in various rotations to each other.

#### What happens:

I can't seem to be able to align the miniblock player heads (mob heads in pure vanilla) in various rotations with each other. They have little offsets that are less than 1/16 of a block. 

#### What you expected to happen:

Have a way to align blocks and heads in various rotations, for example:
Head in hand on surface: 
face up / down, face left / right, face forward / back
Block in hand on surface:
face up / down, face left / right, face forward / back
Item in hand on surface:
face up / down, face left / right, face forward / back

#### Steps to reproduce:

1. Small stand, no gravity.
2. Wear any head.
3. Swap main hand <-> head.
4. Presets - Attention
5. rotate +45 X and Y
6. Repeat steps 1-5 with other stand at the neighbor block
7. rotate -90 Y
8. try to nudge stands together
9. observe frustrating small gaps between heads in hands.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.17.1
- Armor Statues: 2.9

- Single Player and/or Server? server
- Optifine? none

#### Screenshots *(Optional)*
Received result: 
![image](https://user-images.githubusercontent.com/37238771/145585417-fed2fcd2-d420-4ab3-ab8d-0002bc601d1d.png)

Bonus:
Check out this tiniest flying machine possible, it's 1/8 of a block! I wish I could make it exact...
![image](https://user-images.githubusercontent.com/37238771/145580515-4356238a-c8f4-45d2-9277-db9eb6d01625.png)

**Comment by mcfrei** [comment]
I did not add the (bug) label, sorry, I'm new to this github thing.

**Comment by MukiTanuki** [comment]
the newest branch (1.20.5) has 1/10th pixel nudging that should help to better align smaller armor stands.
