### ISSUE TITLE
[BUG] UUID error spawning armor stand millions of blocks away

### ISSUE THREAD

**Issue by thewombatofdoom** [MukiTanuki/armor-statues#9]
#### Issue Description:
Server console receives this error: UUID of added entity already exists: EntityArmorStand['Armor Stand'/186, uuid='291dfbec-2b7b-4c2b-9899-f665ea53af5d', l='ServerLevel[VanillaSurvival]', x=22068880.50, y=1000.00, z=-4185487.50, cpos=[1379305, -261593], tl=22117074, v=false]

#### What happens:

An invisible armor stand appears several million blocks from anything nearby.  We teleported to the location in spectator mode, deleted the armor stand with /kill, and it reappeared with next server cycle.

#### What you expected to happen:

This should not be occurring.

#### Steps to reproduce:

1. Not sure how to reproduce.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.17, and occured in 1.18.1 also.
- Armor Statues: armor statues v2.8.3

- Single Player and/or Server? Server
- Optifine? No

**Comment by thewombatofdoom** [comment]
The armor stand is invisible.

**Comment by MukiTanuki** [comment]
No idea how that would have happened, but I don't think it has anything to do with the datapack?  I'd need more info on how to reproduce the bug in order to fix it, so I'm closing this issue until more info is given.

**Comment by v1-valux** [comment]
I got the same problem:

UUID of added entity already exists: class_1531['Armor Stand'/1643, l='ServerLevel[world]', x=22068880.50, y=1000.00, z=-4185487.50]
UUID of added entity already exists: class_1531['Armor Stand'/1644, l='ServerLevel[world]', x=16562064.50, y=1000.00, z=-22242911.50]

is there a way to fix this?

I teleported to those positions and could kill it with /kill @e[type=minecraft:armorstand,distance=..100]

But after I restart the server, it gets added again.

**Affected Versions (Do not use "latest"):**

    Minecraft: 1.19

    Armor Statues: armor statues v2.8.4

    Single Player and/or Server? Server

    Optifine? No
    
EDIT: created a new Bug-report, as I think closed issues don't get reviewed often(?)
https://github.com/MukiTanuki/armor-statues/issues/12

**Comment by v1-valux** [comment]
Issue Solved, see #12.

cheers
